---
name: boc-coreinfra
services:
  socket-proxy-readonly:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy-readonly
    restart: unless-stopped
    read_only: true
    tmpfs: 
      - /run
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      IMAGES: 1
      DISTRIBUTION: 1
      POST: 1
    networks:
      - socket-proxy-readonly

  socket-proxy-portainer:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy-portainer
    restart: unless-stopped
    read_only: true
    tmpfs: 
      - /run
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      IMAGES: 1
      DISTRIBUTION: 1
      INFO: 1
      NETWORKS: 1
      VOLUMES: 1
      EXEC: 1
      POST: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTARTS: 1
    networks:
      - socket-proxy-portainer

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    networks:
      shared-network:
        ipv4_address: 10.0.0.5
    volumes:
      - /mnt/portainer_ext_vol_01/authelia:/config
    environment:
      AUTHELIA_JWT_SECRET_FILE: /config/secrets/jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/storage_encryption_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.boxingoctopus.io`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=leresolver"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      # Define the forwardauth middleware here, once, for everything to reference
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.boxingoctopus.io"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      - "wud.trigger.include="
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:9091/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  traefik:
    container_name: traefik
    image: "traefik:latest"
    restart: always
    command:
      - --ping=true
      - --ping.entrypoint=ping
      - --entrypoints.ping.address=:8082
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.endpoint=tcp://socket-proxy-readonly:2375
      - --providers.docker.exposedbydefault=false
      - --log.level=ERROR
      - --accesslog=true
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=ryan.draga@boxingoctop.us
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    networks:
      socket-proxy-readonly:
      shared-network:
        ipv4_address: 10.0.0.2
    volumes:
      - "/mnt/portainer_ext_vol_01/traefik/acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.boxingoctopus.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=authelia@docker"
      - "wud.trigger.include="
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:8082/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    command: -H tcp://socket-proxy-portainer:2375
    restart: always
    networks:
      socket-proxy-portainer:
      shared-network:
        ipv4_address: 10.0.0.3
    volumes:
      - /mnt/portainer_ext_vol_01/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.boxingoctopus.io`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"
      - "wud.trigger.include="
    healthcheck:
      test: ["CMD", "/portainer", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3

  whatsupdocker:
    image: getwud/wud:latest
    container_name: wud
    restart: always
    networks:
      socket-proxy-readonly:
      shared-network:
        ipv4_address: 10.0.0.4
    volumes:
      - /mnt/portainer_ext_vol_01/wud:/store
    environment:
      DOCKER_HOST: tcp://socket-proxy-readonly:2375
      WUD_AUTH_BASIC_ADMIN_USER: $WUD_ADMIN_USERNAME
      WUD_AUTH_BASIC_ADMIN_HASH: $WUD_ADMIN_PASSWORD_HASH
      WUD_TRIGGER_DISCORD_BOC_INFRA_ALERTS_URL: $DISCORD_WEBHOOK_URL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`wud.boxingoctopus.io`)"
      - "traefik.http.routers.wud.entrypoints=websecure"
      - "traefik.http.services.wud.loadbalancer.server.port=3000"
      - "traefik.http.routers.wud.service=wud"
      - "traefik.http.routers.wud.tls.certresolver=leresolver"
      - "traefik.http.routers.wud.middlewares=authelia@docker"
      - "wud.trigger.include="
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  socket-proxy-readonly:
    internal: true
  socket-proxy-portainer:
    internal: true
  shared-network:
    name: shared-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1