---
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
    networks:
      shared-network:
        ipv4_address: 10.0.0.5
    volumes:
      - /mnt/portainer_ext_vol_01/boc-coreinfra-compose/authelia/configuration.yml:/config/configuration.yml:ro
      - /mnt/portainer_ext_vol_01/authelia/secrets:/config/secrets
      - /mnt/portainer_ext_vol_01/authelia/database:/config/database
      - /mnt/portainer_ext_vol_01/authelia/users:/config/users
    environment:
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/session_secret
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/secrets/smtp_password
      X_AUTHELIA_CONFIG_FILTERS: template
    labels:
      traefik.enable: "true"
      traefik.http.routers.authelia.rule: "Host(`auth.boxingoctopus.io`)"
      traefik.http.routers.authelia.entrypoints: "websecure"
      traefik.http.routers.authelia.tls.certresolver: "leresolver"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"
      traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:9091/api/verify?rd=https://auth.boxingoctopus.io"
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      wud.trigger.include: ""
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:9091/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  shared-network:
    external: true