---
services:
  valkey:
    container_name: valkey
    image: valkey/valkey:8-alpine
    networks:
      shared-network:
        ipv4_address: 10.0.0.6
    ports:
      - "6379:6379"
    command: ["valkey-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$      # only track real semver tags
      - wud.trigger.include=docker.autoupdate