---
services:
  whatsupdocker:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    networks:
      socket-proxy-readonly:
      shared-network:
        ipv4_address: 10.0.0.4
    volumes:
      - /mnt/portainer_ext_vol_01/wud:/store
    environment:
      WUD_WATCHER_LOCAL_HOST: socket-proxy-readonly
      WUD_WATCHER_LOCAL_PORT: 2375
      WUD_AUTH_OIDC_AUTHELIA_CLIENTID: wud
      WUD_AUTH_OIDC_AUTHELIA_CLIENTSECRET: $WUD_OIDC_CLIENT_SECRET
      WUD_AUTH_OIDC_AUTHELIA_DISCOVERY: https://auth.boxingoctopus.io/.well-known/openid-configuration
      WUD_AUTH_OIDC_AUTHELIA_REDIRECT: "true"
      WUD_TRIGGER_DISCORD_BOCINFRAALERTS_URL: $DISCORD_WEBHOOK_URL
      WUD_REGISTRY_GHCR_PRIVATE_USERNAME: $WUD_GHCR_USERNAME
      WUD_REGISTRY_GHCR_PRIVATE_TOKEN: $WUD_GHCR_TOKEN
    labels:
      traefik.enable: "true"
      traefik.http.routers.wud.rule: "Host(`wud.boxingoctopus.io`)"
      traefik.http.routers.wud.entrypoints: "websecure"
      traefik.http.services.wud.loadbalancer.server.port: "3000"
      traefik.http.routers.wud.service: "wud"
      traefik.http.routers.wud.tls.certresolver: "leresolver"
      #traefik.http.routers.wud.middlewares: "authelia@docker"
      wud.trigger.include: ""
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  socket-proxy-readonly:
    external: true
  shared-network:
    external: true